import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 }, colorScheme: "dark" });
const feil = [];
p.on("console", (m) => m.type() === "error" && feil.push(m.text().slice(0,140)));
p.on("pageerror", (e) => feil.push("PAGEERROR: " + e.message));
await p.goto("http://127.0.0.1:4399/finnes-ikke", { waitUntil: "networkidle" });
await p.waitForTimeout(600);
await p.fill(".kkterm__in", "pris");
await p.press(".kkterm__in", "Enter");
await p.waitForTimeout(3000);
console.log("etter «pris» i 404-terminalen:\n" + (await p.locator(".kkterm__out").innerText()).trim().split("\n").slice(-6).map(l=>"  "+l).join("\n"));
console.log("navigerte bort?", p.url());
console.log("exit-kommando i innfelt modus:");
await p.fill(".kkterm__in", "exit"); await p.press(".kkterm__in", "Enter"); await p.waitForTimeout(400);
console.log("  " + (await p.locator(".kkterm__out").innerText()).trim().split("\n").pop());
await p.screenshot({ path: ".skudd/404-medjs.png" });
console.log("FEIL:", feil.length ? feil : "ingen");
await b.close();
