import { chromium } from "playwright";
const b = await chromium.launch();
const p = await (await b.newContext({ viewport: { width: 390, height: 844 } })).newPage();
p.on("console", (m) => m.type() === "error" && console.log("KONSOLL:", m.text()));
p.on("pageerror", (e) => console.log("SIDEFEIL:", String(e)));
p.on("requestfailed", (r) => console.log("FEILET:", r.url(), r.failure()?.errorText));
p.on("response", (r) => r.status() >= 400 && console.log("HTTP", r.status(), r.url()));
await p.goto("http://127.0.0.1:4441/finnes-ikke", { waitUntil: "networkidle" });
await p.waitForTimeout(800);
await b.close();
