import { chromium } from "playwright";
const [url, ut, tema, y] = process.argv.slice(2);
const b = await chromium.launch();
const c = await b.newContext({ viewport: { width: 1440, height: 900 }, colorScheme: tema === "light" ? "light" : "dark" });
const p = await c.newPage();
await p.goto(url, { waitUntil: "networkidle" });
if (tema === "light") await p.evaluate(() => (document.documentElement.dataset.theme = "light"));
await p.evaluate((v) => scrollTo({ top: +v, behavior: "instant" }), y || 0);
await p.waitForTimeout(900);
await p.screenshot({ path: ut });
await b.close();
