import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, colorScheme: "dark" });
const feil = [];
p.on("console", (m) => m.type() === "error" && feil.push(m.text().slice(0, 120)));
await p.goto("http://127.0.0.1:4399/", { waitUntil: "networkidle" });
await p.waitForTimeout(1200);
const foer = await p.evaluate(() => document.querySelector(".kk-term[data-live] pre")?.textContent?.trim().slice(0, 50));
await p.fill("#url", "nkom.no");
await p.press("#url", "Enter");
await p.waitForTimeout(12000);
const etter = await p.evaluate(() => document.querySelector(".kk-term[data-live] pre")?.textContent?.trim());
console.log("FØR  :", JSON.stringify(foer));
console.log("ETTER:", JSON.stringify(etter?.slice(0, 260)));
console.log("URL  :", p.url());
console.log("feil :", feil.length ? feil : "ingen");
await b.close();
