import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, colorScheme: "dark" });
await p.goto("http://127.0.0.1:4399/", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
await p.screenshot({ path: ".skudd/komp-hero.png" });
await p.evaluate(() => document.querySelector("[data-stabel]")?.scrollIntoView({ block: "center" }));
await p.waitForTimeout(900);
await p.screenshot({ path: ".skudd/komp-om.png" });
await b.close();
