import { chromium } from "playwright";
const [url, ut] = process.argv.slice(2);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 }, colorScheme: "dark" });
await p.goto(url, { waitUntil: "networkidle" });
const f = await p.$("[data-scenefilm]");
await f.scrollIntoViewIfNeeded();
await p.evaluate(() => { const v = document.querySelector("[data-scenefilm] video"); if (v?.duration) v.currentTime = v.duration * 0.92; });
await p.waitForTimeout(1200);
await p.screenshot({ path: ut, clip: await f.boundingBox() });
console.log("tema:", await p.evaluate(() => document.documentElement.dataset.theme ?? "(systemets)"));
await b.close();
