import { chromium } from "@playwright/test";
const ut = process.argv[2], base = "http://127.0.0.1:4399";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1440, height: 900 }, colorScheme: "dark" });
const p = await ctx.newPage();
const feil = [];
p.on("console", (m) => m.type() === "error" && feil.push(m.text()));
await p.goto(base + "/", { waitUntil: "networkidle" });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${ut}/ny-forside-folden.png` });
await p.evaluate(() => window.scrollTo(0, 780));
await p.waitForTimeout(1200);
await p.screenshot({ path: `${ut}/ny-forside-teaser.png` });
await b.close();
console.log("konsollfeil:", feil.length ? feil : "ingen");
