import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 1000 }, colorScheme: "dark" });
const feil = [];
p.on("console", (m) => m.type() === "error" && feil.push(m.text().slice(0, 120)));
await p.goto("http://127.0.0.1:4411/lab/og", { waitUntil: "networkidle" });
await p.waitForTimeout(1200);
await p.screenshot({ path: ".skudd/og-lab.png" });
console.log("bilder på siden:", await p.locator(".card img").count());
console.log("feil:", feil.length ? feil : "ingen");
await b.close();
