import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 1000 }, colorScheme: "dark" });
const feil = [];
p.on("console", (m) => m.type() === "error" && feil.push(m.text().slice(0, 120)));
await p.goto("http://127.0.0.1:4405/lab/ikoner", { waitUntil: "networkidle" });
await p.waitForTimeout(800);
await p.screenshot({ path: "/tmp/ikoner-full.png", fullPage: true });
console.log("ikoner rendret:", await p.locator(".ikonrist svg").count());
console.log("feil:", feil.length ? feil : "ingen");
await b.close();
