import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 2, colorScheme: "dark", reducedMotion: "reduce" });
await p.goto("http://127.0.0.1:4581/lab/interaksjon", { waitUntil: "networkidle" });
await p.locator("[data-slep]").first().scrollIntoViewIfNeeded();
await p.waitForTimeout(700);
await p.evaluate(()=>{const s=document.querySelector("[data-slep-spak]");s.value="62";s.dispatchEvent(new Event("input",{bubbles:true}));});
await p.waitForTimeout(300);
await p.screenshot({ path: ".skudd/opptak-se/slep-169.png", clip: { x:248, y:86, width:1104, height:622 } });
await b.close();
