import { chromium } from "@playwright/test";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1600, height: 900 }, deviceScaleFactor: 2, colorScheme: "dark", reducedMotion: "reduce" });
await p.goto("https://kodekonsulentene.no/", { waitUntil: "networkidle" });
await p.waitForTimeout(700);
await p.keyboard.press("~");
await p.waitForTimeout(500);
const inn = p.locator(".kkterm input").first();
await inn.fill("sjekk kodekonsulentene.no");
await inn.press("Enter");
const t0 = Date.now();
await p.waitForFunction(() => {
  const d = document.querySelector(".kkterm");
  return d && /Lovp|Org\.nr|poeng|100/.test(d.textContent || "");
}, { timeout: 120000 }).catch(() => console.log("  (timeout på ventefunksjon)"));
console.log(`  svar etter ${((Date.now()-t0)/1000).toFixed(1)} s`);
await p.waitForTimeout(600);
const r = await p.evaluate(() => { const d=document.querySelector(".kkterm").getBoundingClientRect(); return {x:Math.round(d.x),y:Math.round(d.y),w:Math.round(d.width),h:Math.round(d.height)}; });
console.log("  endelig boks:", JSON.stringify(r));
await p.screenshot({ path: ".skudd/opptak-se/term-ferdig.png", clip: { x: r.x-20, y: r.y-20, width: r.w+40, height: Math.min(r.h+40, 900-r.y+20) } });
await b.close();
