import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const feil = [];
p.on("pageerror", (e) => feil.push(e.message.slice(0, 80)));
await p.goto(process.argv[2], { waitUntil: "networkidle" });
const f = p.locator("[data-slep-flate]").first();
await f.scrollIntoViewIfNeeded(); await p.waitForTimeout(700);
const inp = p.locator('input[type="range"]').first();
console.log("  accent-color:", await inp.evaluate((e) => getComputedStyle(e).accentColor));
console.log("  spakhøyde:   ", await inp.evaluate((e) => Math.round(e.getBoundingClientRect().height)) + "px");
// Dra på selve skillelinjen, slik hintet lover
const r = await f.boundingBox();
const før = await p.evaluate(() => getComputedStyle(document.querySelector("[data-slep-flate]")).getPropertyValue("--p").trim());
await p.mouse.move(r.x + r.width / 2, r.y + r.height / 2);
await p.mouse.down();
await p.mouse.move(r.x + r.width * 0.25, r.y + r.height / 2, { steps: 14 });
await p.mouse.up(); await p.waitForTimeout(400);
const etter = await p.evaluate(() => getComputedStyle(document.querySelector("[data-slep-flate]")).getPropertyValue("--p").trim());
console.log(`  dra paa linjen: --p ${før} -> ${etter}  ${før !== etter ? "VIRKER" : "INGEN EFFEKT"}`);
console.log("  sidefeil:", feil.length ? feil.join(" | ") : "ingen");
await b.close();
