import { chromium } from "playwright";
import { PNG } from "pngjs";
import { readFileSync } from "node:fs";
const kilde = readFileSync(".skudd/syn3.mjs", "utf8");
const fnTekst = kilde.slice(kilde.indexOf("function tommeRaderFraPiksel"), kilde.indexOf("async function tomrom"));
const fn = new Function("PNG", fnTekst + "; return tommeRaderFraPiksel;")(PNG);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1512, height: 900 }, colorScheme: "dark" });
await p.goto("http://127.0.0.1:4525/om", { waitUntil: "networkidle" });
await p.evaluate(() => scrollTo(0, 0)); await p.waitForTimeout(400);
console.log("resultat:", JSON.stringify(fn(await p.screenshot())));
await b.close();
