import { chromium } from "playwright";
const [base, side, ut] = process.argv.slice(2);
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1512, height: 900 } });
await p.goto(base + side, { waitUntil: "networkidle" });
await p.evaluate(() => document.querySelector("[data-scenefilm]")?.scrollIntoView({ block: "center" }));
await p.waitForTimeout(600);
await p.evaluate(async () => { const v = document.querySelector("[data-scenefilm-video]"); if (v) { v.currentTime = v.duration * 0.75; } await new Promise(r => setTimeout(r, 900)); });
const box = await p.evaluate(() => { const f = document.querySelector("[data-scenefilm]"); const s = f.closest("section") || f.parentElement; const r = s.getBoundingClientRect(); return { x: 0, y: Math.max(0, r.y), width: 1512, height: Math.min(900 - Math.max(0, r.y), r.height) }; });
await p.screenshot({ path: ut, clip: box });
await b.close();
